# Generated by Django 5.2.17 on 2026-09-25 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('category', models.CharField(default='家常菜', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('source_type', models.CharField(default='own', max_length=12)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('source_note', models.TextField(blank=True)),
                ('create_request_id', models.UUIDField()),
                ('create_digest', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=5)),
                ('file_key', models.CharField(max_length=50, unique=True)),
                ('mime_type', models.CharField(max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('upload_request_id', models.UUIDField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_media', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='meals.familyrecipe')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='familyrecipe',
            constraint=models.UniqueConstraint(fields=('created_by', 'create_request_id'), name='unique_family_recipe_request'),
        ),
        migrations.AddConstraint(
            model_name='recipemedia',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'video')), fields=('recipe',), name='one_video_per_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipemedia',
            constraint=models.UniqueConstraint(fields=('created_by', 'upload_request_id'), name='unique_recipe_media_request'),
        ),
    ]
