# Generated by Django 5.2.17 on 2026-09-26 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('shopping', '0002_remove_shoppingitem_shopping_received_has_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familyrecipe',
            name='review_state',
            field=models.CharField(default='needs_review', max_length=16),
        ),
        migrations.AddField(
            model_name='familyrecipe',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='HouseholdTaste',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='one_household_taste')],
            },
        ),
        migrations.CreateModel(
            name='NutritionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=80)),
                ('food_state', models.CharField(default='raw', max_length=16)),
                ('source_name', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('source_url', models.URLField(max_length=600)),
                ('source_version', models.CharField(max_length=40)),
                ('edible_note', models.CharField(blank=True, max_length=160)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('carbohydrate_g', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('total_sugar_g', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('added_sugar_g', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('checked_at', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient_name', 'food_state'), name='unique_nutrition_food_state')],
            },
        ),
        migrations.CreateModel(
            name='RecipeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('raw_text', models.TextField(blank=True)),
                ('conditions', models.JSONField()),
                ('inventory_signature', models.CharField(max_length=64)),
                ('preference_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_ids', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plans', to=settings.AUTH_USER_MODEL)),
                ('recipe_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='meals.reciperequest')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '生成中'), ('validating', '校验中'), ('success', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '超时')], default='queued', max_length=16)),
                ('provider', models.CharField(max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('deadline_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to=settings.AUTH_USER_MODEL)),
                ('recipe_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_tasks', to='meals.reciperequest')),
            ],
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('share_restrictions', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuShoppingContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_version', models.PositiveIntegerField()),
                ('ingredient_name', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_contributions', to='meals.menuplan')),
                ('shopping_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shopping.shoppingitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('menu', 'menu_version', 'ingredient_name', 'unit'), name='unique_menu_purchase_gap')],
            },
        ),
        migrations.CreateModel(
            name='RecipeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_key', models.CharField(max_length=80)),
                ('verdict', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe_key'), name='unique_recipe_feedback')],
            },
        ),
        migrations.AddConstraint(
            model_name='reciperequest',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='unique_recipe_request'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['status', 'created_at'], name='generation_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationtask',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='unique_generation_request'),
        ),
    ]
