# Generated by Django 5.2.17 on 2026-09-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_businessaction_action_kind_valid_and_more'),
        ('meals', '0003_seed_nutrition_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuplan',
            name='executed_action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_menu', to='inventory.businessaction'),
        ),
    ]
