# Generated by Django 5.2.17 on 2026-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_menuplan_executed_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuplan',
            name='actual_nutrition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='menuplan',
            name='actual_uses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
