# Generated by Django 5.2.17 on 2026-10-03 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_invitation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
