# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('lot_create', '录入'), ('lot_edit', '编辑'), ('consume', '使用'), ('discard', '丢弃'), ('shop_receive', '采购入库')], max_length=20)),
                ('params_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity_milli', models.BigIntegerField()),
                ('unit', models.CharField(choices=[('g', '克'), ('kg', '千克'), ('ml', '毫升'), ('l', '升'), ('piece', '个'), ('pack', '包')], max_length=10)),
                ('location', models.CharField(choices=[('fridge', '冷藏'), ('freezer', '冷冻'), ('pantry', '常温'), ('other', '其他')], max_length=10)),
                ('planned_use_date', models.DateField(blank=True, null=True)),
                ('package_date', models.DateField(blank=True, null=True)),
                ('package_date_text', models.CharField(blank=True, max_length=80)),
                ('package_date_status', models.CharField(choices=[('known', '已记录'), ('not_applicable', '不适用'), ('unknown', '未记录')], default='unknown', max_length=16)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '在库'), ('suspect', '疑似变质'), ('discarded', '已丢弃'), ('depleted', '已用完')], default='active', max_length=12)),
                ('storage_status', models.CharField(choices=[('verified', '已核对'), ('needs_check', '待核对')], default='needs_check', max_length=12)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_milli', models.BigIntegerField()),
                ('unit', models.CharField(choices=[('g', '克'), ('kg', '千克'), ('ml', '毫升'), ('l', '升'), ('piece', '个'), ('pack', '包')], max_length=10)),
                ('before_milli', models.BigIntegerField()),
                ('after_milli', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.businessaction')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorylot')),
            ],
        ),
        migrations.AddIndex(
            model_name='businessaction',
            index=models.Index(fields=['actor', '-created_at'], name='action_actor_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessaction',
            constraint=models.UniqueConstraint(fields=('actor', 'request_id'), name='action_actor_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='businessaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['lot_create', 'lot_edit', 'consume', 'discard', 'shop_receive'])), name='action_kind_valid'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['status', 'planned_use_date'], name='lot_status_planned_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['ingredient', 'status'], name='lot_ingredient_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_milli__gte', 0)), name='lot_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['g', 'kg', 'ml', 'l', 'piece', 'pack'])), name='lot_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('location__in', ['fridge', 'freezer', 'pantry', 'other'])), name='lot_location_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspect', 'discarded', 'depleted'])), name='lot_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('storage_status__in', ['verified', 'needs_check'])), name='lot_storage_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('package_date_status__in', ['known', 'unknown', 'not_applicable'])), name='lot_package_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('package_date__isnull', False), ('package_date_status', 'known')), models.Q(('package_date__isnull', True), ('package_date_status__in', ['unknown', 'not_applicable'])), _connector='OR'), name='lot_package_date_consistent'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['lot', '-created_at'], name='movement_lot_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('before_milli__gte', 0)), name='movement_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('after_milli__gte', 0)), name='movement_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('after_milli', django.db.models.expressions.CombinedExpression(models.F('before_milli'), '+', models.F('delta_milli')))), name='movement_balance_matches'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('unit__in', ['g', 'kg', 'ml', 'l', 'piece', 'pack'])), name='movement_unit_valid'),
        ),
    ]
