# Generated by Django 5.2.17 on 2026-09-25 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessaction',
            name='action_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='inventorylot',
            name='lot_qty_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='movement',
            name='movement_before_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='movement',
            name='movement_after_nonnegative',
        ),
        migrations.AlterField(
            model_name='businessaction',
            name='kind',
            field=models.CharField(choices=[('lot_create', '录入'), ('lot_edit', '编辑'), ('consume', '使用（旧类型）'), ('cook', '用于做饭'), ('eat', '直接食用'), ('discard', '丢弃'), ('correct', '库存校正'), ('shop_receive', '采购入库')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='businessaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['lot_create', 'lot_edit', 'consume', 'cook', 'eat', 'discard', 'correct', 'shop_receive'])), name='action_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_milli__gte', 0), ('quantity_milli__lte', 1000000000000)), name='lot_qty_bounded'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('before_milli__gte', 0), ('before_milli__lte', 1000000000000)), name='movement_before_bounded'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(('after_milli__gte', 0), ('after_milli__lte', 1000000000000)), name='movement_after_bounded'),
        ),
    ]
