# Generated by Django 5.2.17 on 2026-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_businessaction_action_kind_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='manual_priority',
            field=models.BooleanField(default=False),
        ),
    ]
