# Generated by Django 5.2.17 on 2026-09-25 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylot_manual_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessaction',
            name='action_kind_valid',
        ),
        migrations.AlterField(
            model_name='businessaction',
            name='kind',
            field=models.CharField(choices=[('lot_create', '录入'), ('lot_edit', '编辑'), ('consume', '使用（旧类型）'), ('cook', '用于做饭'), ('eat', '直接食用'), ('discard', '丢弃'), ('correct', '库存校正'), ('shop_add', '加入采购'), ('shop_bought', '标记买到'), ('shop_cancel', '取消采购'), ('shop_receive', '采购入库')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='businessaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['lot_create', 'lot_edit', 'consume', 'cook', 'eat', 'discard', 'correct', 'shop_add', 'shop_bought', 'shop_cancel', 'shop_receive'])), name='action_kind_valid'),
        ),
    ]
