from django.urls import path

from core import views
from inventory import api as inventory_api, views as inventory_views
from meals import views as meals_views, workbench_views
from shopping import views as shopping_views

urlpatterns = [
    path("", views.index, name="index"),
    path("health/", views.health, name="health"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("settings/", views.household_settings, name="household_settings"),
    path("recipes/", meals_views.recipe_list, name="recipes_page"),
    path("recipes/workbench/", workbench_views.workbench_page, name="workbench_page"),
    path("recipes/workbench/confirm/", workbench_views.confirm_conditions, name="workbench_confirm"),
    path("recipes/workbench/<uuid:plan_id>/", workbench_views.workbench_results, name="workbench_results"),
    path("recipes/workbench/<uuid:plan_id>/menu/", workbench_views.create_menu, name="workbench_menu_create"),
    path("recipes/workbench/<uuid:plan_id>/generate/", workbench_views.generation_submit, name="generation_submit"),
    path("recipes/workbench/<uuid:plan_id>/feedback/<slug:recipe_id>/", workbench_views.recipe_feedback, name="recipe_feedback"),
    path("recipes/workbench/menu/<uuid:menu_id>/", workbench_views.menu_detail, name="menu_detail"),
    path("recipes/workbench/menu/<uuid:menu_id>/shopping/", workbench_views.menu_add_shopping, name="menu_add_shopping"),
    path("recipes/workbench/menu/<uuid:menu_id>/cook/", workbench_views.menu_cook, name="menu_cook"),
    path("recipes/generation/<uuid:task_id>/", workbench_views.generation_detail, name="generation_detail"),
    path("recipes/generation/<uuid:task_id>/status/", workbench_views.generation_status, name="generation_status"),
    path("recipes/generation/<uuid:task_id>/cancel/", workbench_views.generation_cancel, name="generation_cancel"),
    path("recipes/generation/<uuid:task_id>/save/", workbench_views.generation_save, name="generation_save"),
    path("recipes/preferences/", workbench_views.taste_profile, name="personal_taste"),
    path("recipes/preferences/household/", workbench_views.taste_profile, {"scope": "household"}, name="household_taste"),
    path("recipes/new/", meals_views.recipe_new, name="recipe_new"),
    path("recipes/<slug:recipe_id>/", meals_views.recipe_detail, name="recipe_detail"),
    path("recipes/<slug:recipe_id>/edit/", meals_views.recipe_edit, name="recipe_edit"),
    path("recipes/<slug:recipe_id>/upload/", meals_views.recipe_upload, name="recipe_upload"),
    path("recipes/<slug:recipe_id>/media/<uuid:media_id>/", meals_views.recipe_media_file, name="recipe_media_file"),
    path("recipes/<slug:recipe_id>/media/<uuid:media_id>/delete/", meals_views.recipe_media_delete, name="recipe_media_delete"),
    path("recipes/<slug:recipe_id>/cook/", meals_views.recipe_cook, name="recipe_cook"),
    path("shopping/", shopping_views.shopping_page, name="shopping_page"),
    path("shopping/<int:item_id>/bought/", shopping_views.shopping_bought, name="shopping_bought"),
    path("shopping/<int:item_id>/cancel/", shopping_views.shopping_cancel, name="shopping_cancel"),
    path("shopping/<int:item_id>/receive/", shopping_views.shopping_receive, name="shopping_receive"),
    path("api/settings/", views.household_settings_api, name="household_settings_api"),
    path("inventory/", inventory_views.inventory_page, name="inventory_page"),
    path("inventory/action/", inventory_views.action_form, name="inventory_action_form"),
    path("inventory/<int:lot_id>/edit/", inventory_views.edit_page, name="inventory_edit_page"),
    path("api/inventory/", inventory_api.inventory_collection, name="inventory_api"),
    path("api/inventory/recognize/", inventory_api.recognize_photo, name="inventory_recognize_api"),
    path("api/inventory/<int:lot_id>/", inventory_api.inventory_detail, name="inventory_detail_api"),
    path("api/actions/", inventory_api.actions_collection, name="actions_api"),
    path("api/actions/<int:action_id>/", inventory_api.action_detail, name="action_detail_api"),
    path("api/actions/by-request/<uuid:request_id>/", inventory_api.action_by_request, name="action_by_request_api"),
    path("api/today/", views.today_api, name="today_api"),
    path("api/recipes/", meals_views.recipe_list_api, name="recipes_api"),
    path("api/shopping/", shopping_views.shopping_api, name="shopping_api"),
    path("api/shopping/<int:item_id>/bought/", shopping_views.shopping_bought_api, name="shopping_bought_api"),
    path("api/shopping/<int:item_id>/cancel/", shopping_views.shopping_cancel_api, name="shopping_cancel_api"),
    path("api/shopping/<int:item_id>/receive/", shopping_views.shopping_receive_api, name="shopping_receive_api"),
    path("api/movements/", inventory_api.movements_collection, name="movements_api"),
]
