# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity_milli', models.BigIntegerField()),
                ('unit', models.CharField(choices=[('g', '克'), ('kg', '千克'), ('ml', '毫升'), ('l', '升'), ('piece', '个'), ('pack', '包')], max_length=10)),
                ('status', models.CharField(choices=[('needed', '待采购'), ('bought', '已买到'), ('received', '已入库'), ('cancelled', '已取消')], default='needed', max_length=12)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient')),
                ('received_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_receipt', to='inventory.businessaction')),
                ('received_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_source', to='inventory.inventorylot')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='shopping_status_recent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_milli__gt', 0)), name='shopping_qty_positive'), models.CheckConstraint(condition=models.Q(('unit__in', ['g', 'kg', 'ml', 'l', 'piece', 'pack'])), name='shopping_unit_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['needed', 'bought', 'received', 'cancelled'])), name='shopping_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('received_action__isnull', False), ('received_lot__isnull', False), ('status', 'received')), models.Q(('status', 'received'), _negated=True), _connector='OR'), name='shopping_received_has_result')],
            },
        ),
    ]
